### ISSUE TITLE
'Area' Light makes dark reflection

### ISSUE THREAD

**Issue by sus-unn** [LuxCoreRender/LuxCore#110]
![image](https://user-images.githubusercontent.com/36620824/40168896-aaef1e86-59ff-11e8-88ed-6020aea9a2a8.png)
You can see it in the left preview panel.

In the left panel is light's properties.

Objects should reflect light's color(in this case, white) like in cycles.

- Currently using luxcore 2.0

- I am not uploading blend file because this happens always.

**Comment by Theverat** [comment]
The brightness of your area lamp is too low.
Raise the gain, power, or efficacy until it appears white.

**Comment by Dade916** [comment]
Yup, sky light source emits a LOT of power and your lamp has only 2 Watt.

**Comment by sus-unn** [comment]
Oh, the area light behaves differently from cycles. I cranked up the gain and now it works. Thanks.

**Comment by Theverat** [comment]
Yes, it is a plane mesh with light emitting matte material.
The matte diffuse color is set to black to prevent bounce light from the mesh (it would be weird if another light source would make the area light appear brighter due to indirect light bouncing off it's surface).
That's why it appears black when the emitted light is not enough.
