### ISSUE TITLE
dark edges on glossy materials 

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#146]
From time to time as I create materials I notice shaders looking wrong and when I start comparing the looks with cycles I always find the same issue to be the biggest problem.
Glossy material with higher roughness values creates dark outlines that make shader look very wrong.
Enabling multibounce somewhat helps, but not completely and I think the black outline shouldn't be on glossy material in any case. 
![luxcoreedges](https://user-images.githubusercontent.com/43474911/47267636-02baf000-d547-11e8-8979-f7d49eed0f56.jpg)
[LUXCORE_GI_PERF_TEST.zip](https://github.com/LuxCoreRender/LuxCore/files/2499173/LUXCORE_GI_PERF_TEST.zip)

**Comment by Dade916** [comment]
The problem is noticeable when setting a glossy material as a matte material with KS = black and roughness = 1.0.

This is a matte rendering:

![matte](https://user-images.githubusercontent.com/3247881/47614591-9ee27b00-daa2-11e8-95cf-30ed7d175108.png)

and this is a glossy-set-as-matte:

![glossy](https://user-images.githubusercontent.com/3247881/47614590-9ee27b00-daa2-11e8-8f04-dd8bfd94107a.png)

The problem is also visible only for indirect lighting. This is the same test done with an area light. This is a matte rendering:

![matte](https://user-images.githubusercontent.com/3247881/47614619-faad0400-daa2-11e8-9f8b-5dde3f1e7fe4.png)

and this is a glossy-set-as-matte:
![glossy](https://user-images.githubusercontent.com/3247881/47614618-faad0400-daa2-11e8-93ca-510f4bbd6ef8.png)

So the problem is likely to be in glossy Material::Sample() method.

**Comment by Dade916** [comment]
I have fixed a problem affecting only the OpenCL code. Were you doing the renderings using OpenCL ?

Note: increasing also max. glossy depth slightly reduce the "black halo" because the default is only 4 and it is quite low for this scene where also the walls are glossy and all light is indirect.

This is the result (no multi-bounce):

![glossy2](https://user-images.githubusercontent.com/3247881/47618294-a1a89480-dad1-11e8-978f-708b1652c11c.png)

It looks correct to me (differences due to not using GGX micro-facet aside, as explained by Patrick).
