### ISSUE TITLE
External dependencies

### ISSUE THREAD

**Issue by waebbl** [LuxCoreRender/LuxCore#159]
Hi, I'm currently working on an ebuild (i.e. packaging) of LuxCore for Gentoo Linux and got some questions on the build.

1. There are a few dependencies located in the `deps` dir, which are needed by the app. Yet, some of those deps are well known packages, probably provided by any modern linux distribution, i.e. `eigen` and `openvdb`. I suspect, most users who are installing a piece of software like LuxCore will already have those installed as a dependency of other, similar apps, like `blender`. Can the system packages be used to build LuxCore or is this currently not possible?

2. Do you have plans to provide an install target for cmake?

**Comment by Dade916** [comment]
About #1, we have static build procedure (described here: https://github.com/LuxCoreRender/LinuxCompile), it has been developed to be able to distribute Linux binaries and avoid all the problems related version incompatibilities/availability across different Linux distributions. It is required because we need specific package versions.
The libraries included in apps are usually both small and (some time) a modified version of the original package. They also simplify the compilation across Linux/Windows/MacOS. So the short answer to #1 is nope.

About #2, the building procedure at https://github.com/LuxCoreRender/LinuxCompile delivers a .tar.bz2 for the default standalone installation. It is just a directory including everything, it doesn't need any particular installation procedure.

The Blender plugin is available as a .zip like other plugins (https://wiki.luxcorerender.org/BlendLuxCore_Installation) , it is packaged using the above binaries  and https://github.com/LuxCoreRender/BlendLuxCore (it includes a script to pack the .zip: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/doc/release.md).

**Comment by waebbl** [comment]
Thanks for your answer. Not unpacking external packages and using the packaged ones will be fine to get started.

I already looked at the LinuxCompile repo, but this is not of much use for Gentoo. Gentoo is a source based distribution, so we don't deliver packaged binaries, but instead we deliver scripts (called ebuild) to our users, which they pass to the package manager to compile a piece of software for their purpose, i.e. their machine configuration, optional packages, compiler used, compile and links flags and so on. So we already provide a complete, sandboxed build environment, which has to be used when building packages. Also, using the LinuxCompile task would mean, to install packages like jpeg, tiff, libpng or Qt inside an `/opt` environment (i.e. a self contained software) which is only usable by the piece of software that built it. But usually those packages are already installed on the system in question and used by lots of other software, so there's no need to compile them again, only for one software and would waste a lot of compilation and HD resources.

I had no problem compiling LuxCore, once all dependencies were installed, I was only missing an easy way to install it. I will need to setup a manual install then, using the install script from LinuxCompile as a reference, or patch the CMakeLists.txt with install targets.
Thanks again for your answer!
