### ISSUE TITLE
Samples/sec are very low until first convergence test runs

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#163]
I have observed now multiple times the following behaviour:
When combining OpenCL, the denoiser and the convergence test, the reported Samples/sec are very low until the first convergence test runs.
For example, in this screen capture, the samples/sec start out with around 650 k, go down to 100 k, and jump back to 670 k once the first convergence test is done:
https://youtu.be/OY44AXPmQ6U
(warmup samples is set to 4, and test step samples is set to 8)

Here is a test scene:
https://drive.google.com/open?id=1hjd467bzRG0MhOLS1vg--zhlXw5wVgAk
You may have to change the .cfg so it works on your GPU configuration.

Is this only a displaying problem (so the samples/sec don't go down interally, they are just reported wrong), or is the rendering really slower until the first convergence test?

By the way, for some reason the densitygrid data is embedded as text in the .scn file even though it is also serialized as an imagemap (so it's duplicated).

**Comment by Dade916** [comment]
I don't think it is related to convergence test but it is instead the normal result of the auto-tuning of the CPU image download timing: https://github.com/LuxCoreRender/LuxCore/blob/a83bb1118b6240445947ea7d869dcc68974094ba/src/slg/engines/pathocl/pathoclopenclthread.cpp#L141

It works like network rendering: when you download the rendered image, there is a spike in samples/sec and then go slowly down up to the next download.

If you check the code, you will see it tries to keep the time spent downloading the image under the 1% of the total time. This can lead to huge spikes if the download interval is long.

Hybrid rendering can samewhat hide/confuse this behavior because the samples are added in real time when rendered on the CPU. Try to disable hybrid cpu rendering, use a large image resolution and the "saw" behavior should be very visible.

**Comment by Theverat** [comment]
Thanks for the explanation.
