### ISSUE TITLE
"RuntimeError: clGetPlatformIDs" in Python sample code

### ISSUE THREAD

**Issue by JayFoxRox** [LuxCoreRender/LuxCore#191]
When I run the Python demos, I get the following errors:

```
Traceback (most recent call last):
  File "../samples/pyluxcoredemo/pyluxcoredemo.py", line 674, in <module>
    main()
  File "../samples/pyluxcoredemo/pyluxcoredemo.py", line 661, in main
    LuxRaysDeviceTests()
  File "../samples/pyluxcoredemo/pyluxcoredemo.py", line 142, in LuxRaysDeviceTests
    deviceList = pyluxcore.GetOpenCLDeviceList()
RuntimeError: clGetPlatformIDs
```

This happens for pyluxcoredemo, pyluxcoreserializationdemo and pysideluxcoredemo.

I did not check wether this issue also exists in the C++ code.

**Environment**

I have the following packages installed in my Arch Linux installation:

* ocl-icd 2.2.12-3 (OpenCL ICD Bindings)
* opencl-headers 2:2.2.20170516-2 (OpenCL (Open Computing Language) header files)

I have built LuxCore through https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=luxcorerender

**Workaround**

I can work around this issue by installing:

* beignet 1.3.2+12+gfc5f430c-2 (An open source OpenCL implementation for Intel IvyBridge & Haswell iGPUs)

I believe that LuxCore should be able to dynamically link - checking for availability at runtime - against OpenCL, and should also be able to handle the situation where no OpenCL is installed, or OpenCL is installed without a device driver.

I do not want to disable OpenCL at compile-time (as was suggested in other issues): this is a problem with LuxCore that should be addressed.

**Comment by Dade916** [comment]
As you already know, you need to install and run the OpenCL-less version of LuxCoreRender if you want to work on an platform where OpenCL is not available.
As work around you can solve the problem at Python level importing the OpenCL or the OpenCL-less pyluxcore.so according your needs.

I'm not aware of an generic/not OS specific way of solving this problem (at C++ level). If someone want try to solve this problem, sure, be my guest, otherwise I don't plan to look into this topic for a foreseeable future.

**Comment by JayFoxRox** [comment]
How is OpenCL actually used in LuxCore? Where is it actually being called? I did grep for `clGetPlatformIDs` and surprisingly found nothing.

I might look into OpenCL loaders / possible solutions to this, but I'll probably need some guidance.
