### ISSUE TITLE
Is Embree really required for building LuxCore?

### ISSUE THREAD

**Issue by cesss** [LuxCoreRender/LuxCore#206]
I'm a bit confused about the Embree dependence when building LuxCore. AFAIK, Embree and OpenCL are radically different: the former requires an Intel CPU, while the later will run on _**any CPU**_ and _**any GPU**_ that supports OpenCL.

Can you build LuxCore disabling the Embree requirement and depending only on OpenCL? I would prefer not to depend on Embree, first because my code is CPU-independent, and second because the fact that triangle mesh raytracing [is still broken](https://github.com/embree/embree/issues/174) in Embree even after more than a year that the bug was reported, makes me feel that Intel is not investing much on that project (IMHO, such a bug deserves a _showstopper_ tag for a final release of any serious raytracer).

**Comment by Theverat** [comment]
Embree does not require an Intel CPU.

**Comment by Dade916** [comment]
Embree works both on Intel and AMD CPUs or are you trying to compile on a not x86 architecture ?

Anyway, Embree is used by default to fast build the BVH (the structure to accelerate ray/triangles intersections) on the CPU, the BVH structure is than transferred to the GPU and used by our OpenCL code for ray/triangles intersections.

The same BVH building process is also used in other contexts: like for indirect light cache building, etc.

LuxCore supports alternative ray/triangles intersections builders/accelerators: https://github.com/LuxCoreRender/LuxCore/tree/master/include/luxrays/accelerators

However, back to the first question, do you want just avoid to use Embree code path or you can't use Embree because it is not available for your CPU architecture ?

**Comment by cesss** [comment]
In this moment all my production machines are x86. However, my source code (for my tools) has been built on MIPS, PowerPC, and Intel throughout the years. One lesson I learnt from experience is to never make your code depend on an architecture or on a given OS, and I always follow that rule now (I'm glad to support CPU-dependent and GPU-dependent optimizations, but **provided that it's possible to build the code in any CPU architecture if needed**).

I foresee a reasonable probability that I'll be using non-Intel CPUs some years from now.

Given that you are using Embree for BVH only, I suppose it might be possible to do a custom Embree fork with just the needed BVH code, which I suppose should be able to build on any CPU.

Anyway, if it's possible to build LuxCore completely disabling the Embree requirement, tell me how to do so, because I don't have time now for doing that custom Embree fork.

**Comment by Dade916** [comment]
I guess we can close this one.
