### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#236]
Hi, the user **Bernix** has reported this crash.
I can reproduce it as well. It might be Nvidia-driver related, because I think it crashed my driver the third time I reproduced it (screen + audio went offline for a few seconds).

His specs:
Windows
3700X + 1070ti

My specs:
Windows 10
AMD Ryzen 7 2700x
Nvidia RTX 2080

The scene (just open with Blender 2.80 and latest BlendLuxCore and press F12): 
[Test_Caustic_TO_SEND_.zip](https://github.com/LuxCoreRender/LuxCore/files/3617996/Test_Caustic_TO_SEND_.zip)

End of the log (unfortunately not very helpful):
```
[LuxCore][51.422] Starting 0 native render threads
Session started in 23.0 s
Error   : Unrecognized Exception
Address : 0x00007FF932D3A839
Module  : C:\WINDOWS\System32\KERNELBASE.dll

C:\Users\Simon>
```

**Comment by Dade916** [comment]
Roughglass transmit is GLOSSY so there be no caustics because the roughness is 0.0500000007 and the threshold is 0.048999998718500137 (note the rounding problems, the user has probably typed 0.5 in both cases).

Now the empty caustic cache was causing the crash, it was a memory fault on GPU that some hardware/software handles better, some worse (i.e system crash).

I should have fixed the problem.

**Comment by Theverat** [comment]
Confirmed, crash is gone.
