### ISSUE TITLE
New complete Bidirectional path tracing with vertex merging [$50]

### ISSUE THREAD

**Issue by Dade916** [LuxCoreRender/LuxCore#243]
New complete Bidirectional path tracing with vertex merging: a rework of BIDIRCPUVM.

**Comment by Acrivec** [comment]
What does exacly this do?

**Comment by epileptrolytics** [comment]
I'm not really happy with the SDS-cache implementation because it doesn't help with caustics from indirect light as BiDirVM does but given the state of the project I accept this solution as it is and am okay with my bounty on [Bountysource](https://www.bountysource.com/issues/81508162-new-complete-bidirectional-path-tracing-with-vertex-merging) going to @Dade916 for BiDir + SDS-cache.

**Comment by Dade916** [comment]
Anyway I'm donating all the money, of the Bounties I have collected, back to the project. We are also moving away from BountySource because it becoming less and less reliable.
