### ISSUE TITLE
Latest Linux daily builds compiled without OpenCL

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#254]
I have received two independent reports that the latest OpenCL Linux daily builds are apparently compiled without OpenCL support:

![OpenCL](https://user-images.githubusercontent.com/1584761/68013115-644e8800-fc8c-11e9-9852-5afb5317377f.jpeg)
This message in Blender means that `pyluxcore.GetPlatformDesc().Get("compile.LUXRAYS_DISABLE_OPENCL").GetBool()` returned `True`.

One of the reporters says LuxMark 4 is running fine on all GPUs.
One of the last working daily builds was apparently the one from 15.10.2019, although it's not clear that was the last one.

**Comment by Dade916** [comment]
I have downloaded BlendLuxCore-latest-linux64-opencl.zip and it is working fine here with PATHOCL. 

So or was something temporary due to the (very common) Azure fails to upload the .tgz or the user is installing the wrong version.

**Comment by maj3dk** [comment]
It still doesnt work for me. Latest working build is from 15.10.2019. OS Linux Ubuntu 18.04 with latest Nvidia drivers.
![OpenCL_w](https://user-images.githubusercontent.com/57316561/68084160-50dd2180-fe32-11e9-8d66-d2afcebb9873.jpeg)

**Comment by Dade916** [comment]
The only possible explanation is that Blender finds first a pyluxcore.so compiled without OpenCL instead of the one you are downloading and installing (or I have a pyluxcore.so compiled with OpenCL somewhere and it is used first than the one I'm downloading and installing).

Try this:

1) download https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-linux64-opencl.zip
2) execute "unzip BlendLuxCore-latest-linux64-opencl.zip"
3) execute "cd BlendLuxCore/bin"
4) execute "python3"
5) type "import pyluxcore" and press enter
6) type "pyluxcore.GetPlatformDesc().Get("compile.LUXRAYS_DISABLE_OPENCL").GetBool()"

Do you get "True" or "False" as answer ?

My test:

```
david@i7-3930k:~/tmp/ocl/BlendLuxCore/bin$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyluxcore
>>> pyluxcore.GetPlatformDesc().Get("compile.LUXRAYS_DISABLE_OPENCL").GetBool()
True
>>> 
```

**Comment by Theverat** [comment]
@Dade916 Your test seems to confirm the problem, is that correct?

**Comment by Dade916** [comment]
Yes, it is why a deleted my previous post, I have to check what is going wrong.

**Comment by Dade916** [comment]
Ok, I have found the problem, the OpenCL C++ bindings header was missing:

`ERROR--> Could not locate required OpenCL files, disabling OpenCL support - Please check `

And the OpenCL binaries where built without OpenCL.

I'm testing the fix.

**Comment by Dade916** [comment]
The build looks ok now.

**Comment by maj3dk** [comment]
Confirmed. Its working now. Thanks
