### ISSUE TITLE
All materials get assigned the same ID when no ID is specified

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#296]
Scene: [matid_color.zip](https://github.com/LuxCoreRender/LuxCore/files/4128852/matid_color.zip)
LuxCore version: v2.3beta1

The material properties in this scene do not define the ".id" property of the four materials. So they should be assigned pseudo-random IDs [during material parsing](https://github.com/LuxCoreRender/LuxCore/blob/8cd347ed0e34cac4590cd09c95d5b8870324ffa8/src/slg/scene/parsematerials.cpp#L93) in LuxCore, but all of them end up with the same ID.
When exported with FILESAVER, you can see that all materials get the ID 4012384.
To reproduce, just render the scene and you will see the following material ID color AOV:

![untitled](https://user-images.githubusercontent.com/1584761/73370348-5e306d80-42b4-11ea-9e12-f1cd52ff96e4.png)

**Comment by Dade916** [comment]
It has always worked in this way: the random ID was based on the material count so, when you define a new material you get a new random ID. However if you re-define a material, the material count doesn't change so you get the same random ID.

Now, BlendLuxCore is defining all material once (where they get a random ID) and then, redefine them all over again (and they get the same ID because the total material count doesn't change). Why to define all the materials 2 times ?

Anyway, I have fixed the problem and now you should get a random ID even when you re-define a material.

**Comment by Theverat** [comment]
> Now, BlendLuxCore is defining all material once (where they get a random ID) and then, redefine them all over again (and they get the same ID because the total material count doesn't change). Why to define all the materials 2 times ?

Ok, so this is in fact a bug in BlendLuxCore. I'll check what's going on there.

**Comment by Theverat** [comment]
This regression in the addon is caused by the following:

First I export every object that is not instanced, and the first of each group of similar instances.
Then I need to parse their properties into the scene so they are available for the next step, where I use DuplicateObject() to duplicate the instance groups.

After this, motion blur is handled and applied to the same properties already parsed, and then these updated properties are parsed again into the LuxCore scene (re-defining all objects, materials, lights).

So, the main problem is motion blur handling. I'll check if I can move this before the scene.Parse() for DuplicateObjects(), which might be required anyway for motion blur support of instances.

**Comment by Dade916** [comment]
I assume we can close this one because the LuxCore issue has been fixed.
