### ISSUE TITLE
Different Reflection Between Preview and render

### ISSUE THREAD

**Issue by insertcoindottv** [LuxCoreRender/LuxCore#309]
[https://cdn.discordapp.com/attachments/476392073822470154/680051200401735683/unknown.png](url)

**Comment by insertcoindottv** [comment]
Hei Dade, can you see the link?

**Comment by Dade916** [comment]
Are you using the same max. path depth settings ? Preview has, by default, a lot shorter paths.

**Comment by insertcoindottv** [comment]
in discord you can find the scene file if you want to check by yourself

**Comment by Dade916** [comment]
Ok.

**Comment by insertcoindottv** [comment]
Grazie :D

**Comment by Theverat** [comment]
It would be great if you could attach the file here (or paste a link into the first post if it is too big).
The same for the image showing the problem.

**Comment by insertcoindottv** [comment]
![unknown](https://user-images.githubusercontent.com/36404492/76516911-93f07680-645c-11ea-99f2-2c98ddddd361.png)
[http://web.insertcoin.tv:82/Export_LUX_09.7z](url)

**Comment by insertcoindottv** [comment]
Here we are B.

**Comment by Theverat** [comment]
I also have a scene here showing a similar difference in reflection brightness: [ProceduralLeaves_negative_scale_difference.zip](https://github.com/LuxCoreRender/LuxCore/files/4329586/ProceduralLeaves_negative_scale_difference.zip)
It is most likely caused by the combination of two factors:
* Negative scale on some axis. In my scene, it's the x-axis.
* In viewport renders, the objects are instanced, meaning the transformation is applied on the object level and not baked into the mesh. In final renders, the transformation is baked into the mesh and no longer present on the object level.

![Capture](https://user-images.githubusercontent.com/1584761/76621969-d5525600-6530-11ea-96c3-369b4cbb42fa.PNG)

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by insertcoindottv** [comment]
Thank you Dade!
I'll try it asap.
Have a nice day, and stay safe.
Grazie, ciao!
Massimo.
