### ISSUE TITLE
Add Light Tracing randomly quits working

### ISSUE THREAD

**Issue by steveernst117** [LuxCoreRender/LuxCore#312]
#### System Information

Windows 10, 2x GeForce GTX 660 Ti, Intel Xeon CPU ES-2687W v3 @ 3.10GHz

#### Software Version

* Blender version: 2.82 Official release
* LuxCore version: 2.3

#### Short description of error

The Add Light Tracing feature functions inconsistently. Sometimes, it seems as though the intensity of the caustics depends on how zoomed in/out I am when viewport rendering. Other times, it quits working altogether for no discernible reason. Sometimes it works in the viewport render but won't work on f12 render. I can't figure out any sort of reason, or correlation with any other render settings. Sometimes just switching the checkbox on and off will screw it up. 

#### Exact steps for others to reproduce the error
Since I can't deduce what's causing the problem, I can't reproduce the steps, unfortunately.

I've tried rendering in both CPU and OpenCL mode, neither had any noticeable effect. 
[add_light_tracing_bug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4352302/add_light_tracing_bug.zip)

**Comment by steveernst117** [comment]
Yep, that's one of the issues all right. When in render view, do you also notice a difference in caustic intensity depending on how zoomed in/out you are? For me, it gets more intense the further away I get. As I get closer, it tends to decrease/disappear.

**Comment by Theverat** [comment]
Yes, I observe the same in the viewport.

**Comment by Dade916** [comment]
RTPATHCPU (the render engine used by default for view port rendering) doesn't support light tracing at all, the option is simply ignored.

So, I assume, the difference is due to comparing normal Path tracing Vs. Path+Light tracing. Or are you using a different render engine for the view port ?

As a trivial test, try to use a point light source: path tracing will be totally unable to render any caustics while Path+Light tracing will render fine.

**Comment by steveernst117** [comment]
Okay, adding an actual sun lamp helped with getting caustics in f12 render. I still notice the intensity change depending on distance when viewport rendering, but not to such a dramatic degree with the sun lamp. It's still there with a regular point lamp, though. 
So I'm guessing now that the main issue has to do with how the light tracing option handles HDRI lighting...?

**Comment by Theverat** [comment]
> RTPATHCPU (the render engine used by default for view port rendering) doesn't support light tracing at all, the option is simply ignored.
So, I assume, the difference is due to comparing normal Path tracing Vs. Path+Light tracing. Or are you using a different render engine for the view port ?

The scene is set up to use Path CPU + Sobol + light tracing in the viewport.

**Comment by Dade916** [comment]
The problem is likely to be related to the use of a small object over a very large surface (the ground => very large scene bounding box) and Env. light source.

It works fine if you use only point light source in the same scene:

![Screenshot from 2020-04-02 14-10-32](https://user-images.githubusercontent.com/3247881/78247971-16180c00-74ec-11ea-950c-62e51ae9c4d8.png)

I'm looking into this problem.

**Comment by Dade916** [comment]
BTW, zooming out can increase the scene bounding box because the camera is part of the scene. This explain the strange zoom in/out problem you are observing.

**Comment by Dade916** [comment]
I fixed a first problem: due to the size of the scene, Metropolis sampler was finding only 1 useful light path out 250.000 (!). As result, the estimated average image intensity during the warm up phase was totally wrong and this will break all subsequent samples.
Metropolis sampler will now print a warning if it is unable to estimate  the average image intensity with a decent precision:

> Metropolis sampler had only 196 not black samples over a total of 50000011 samples. The rendering may be inaccurate because how hard is to estimate the average image intensity.

Now, the final rendering of this scene should be correct.

There is still a problem with view port rendering because, apparently, a camera edit is not resetting the Metropolis average image intensity. I'm going to fix this too.

**Comment by steveernst117** [comment]
Hey, thanks for working on this! Great to see you're making progress!
So the problem with the imprecise metropolis sampler is an under-the-hood thing and not a scene setup thing?

**Comment by Dade916** [comment]
> There is still a problem with view port rendering because, apparently, a camera edit is not resetting the Metropolis average image intensity. I'm going to fix this too.

I fixed this problem too.

**Comment by Dade916** [comment]
> Hey, thanks for working on this! Great to see you're making progress!
> So the problem with the imprecise metropolis sampler is an under-the-hood thing and not a scene setup thing?

Yes but it was the scene to exacerbate/highlight the problem: if you reduce the size of the ground plane, the problem will become less and less noticeable.

**Comment by steveernst117** [comment]
Okay, interesting. Thanks again for ironing out this issue!
