### ISSUE TITLE
Small light source gradient issues.

### ISSUE THREAD

**Issue by Julien-Peeters** [LuxCoreRender/LuxCore#315]
When a light source is 1cm or smaller, i usually get stepping in the gradients of surfaces. This seems to be resolved in V2.3? But i also noticed crashing with V2.3... (complete system lockup and display issues (screen going black etc.))

**Comment by Theverat** [comment]
If it is already resolved, why do you make it the title of your bug report?
Shouldn't it be "LuxCore crashes"?
Anyway, please upload a scene that shows the crashes, with steps how to reproduce them.

Some info about your OS and GPU would be good too. Also, are you rendering on CPU or GPU?

**Comment by Dade916** [comment]
The bands are likely to be a self-shadow problem due to (lack of) numerical precision. We can not tell you more without a screenshot.

Is it a Blender crash or a a system lockup ? A system lockup is likely to be a driver or hardware problem: an application outside kernel space can not crash an OS (.... in theory).

**Comment by Julien-Peeters** [comment]
i found the problem with the stepping, it only happens when the light source was too small. the system crash was my fault, i apparently had something else running in the background
