### ISSUE TITLE
Crash blender with blenderluxcore 2.3 and texture exr

### ISSUE THREAD

**Issue by useranty** [LuxCoreRender/LuxCore#318]
.blend file: 

Steps to reproduce:

simply scene with cube, light, camera material matte and texture exr

Screenshots or rendered images:

Error message from Blender console:

[Engine/Final] Rendering layer "View Layer"
[Exporter] Creating session
[SDL][11.159] Camera type: perspective
[SDL][11.159] Camera position: Point[7.35889, -6.92579, 4.95831]
[SDL][11.159] Camera target: Point[6.70733, -6.31162, 4.51304]
[SDL][11.159] Camera clipping plane disabled
[SDL][11.163] Texture definition: 139809125227832Color
[SDL][11.163] Reading texture map: /home/xxxx/test/blender/../textures/14textures.exr
Writing: /tmp/lux23_test0001.crash.txt
Segmentation fault

OS: Linux Debian 10 64bit, 
Blender version: 2.82a 64bit
LuxCore version: 2.3

blender 2.82a with luxcore 2.2 and exr work without crash

**Comment by Dade916** [comment]
It is quite strange, the scene crash with any EXR file, not just with one included. Even with EXR files that work fine in other scene. The same test work fine with a PNG.
Exporting the scene and than rendering with LuxCoreUI works fine, even with the original EXR.

It looks like using an EXR as a texture, in BlendLuxCore, in any scene, trigger a crash at rendering ?!?

P.S. this may have been never noticed because EXR are used only for infinite lights by everyone.

**Comment by Dade916** [comment]
At the moment EXR file reading is not working at all for me on Linux. I assume this is a Linux only problem.

**Comment by Dade916** [comment]
I can confirm that the scene works fine on Windows with Blender v2.82a and latest BlendLuxCore build  so it is a Linux-only problem.

**Comment by Dade916** [comment]
I should have fixed the problem. It was a mess of conflicts between LuxCore OpenEXR and Blender OpenEXR global symbols plus broken std::regex on Linux.
