### ISSUE TITLE
Custom textures as shared libraries ?

### ISSUE THREAD

**Issue by melMass** [LuxCoreRender/LuxCore#326]
Hi,

I recently started to use LuxCore extensively and I was wondering if there is a plan to add support for textures as shared library?
Allowing a much cleaner way to add new textures than editing all the files currently required now, I think, but also and most importantly to me, being able to share them easily with users using the packaged version.

Thanks

**Comment by Dade916** [comment]
Many years ago, the old LuxRender had the support for the dynamic loading various types of plugins. We dropped this feature because all the problems we had maintaining the compatibility across all OS (i.e. Windows, Linux and MacOS).

LuxCoreRender has an additional problem compared to old Lux: OpenCL support. With OpenCL, you would have to include your custom texture OpenCL C kernel code inside your plugin and LuxCore would have to recompile all the OpenCL kernels every time you load a new custom textures.
OpenCL Kernel recompilations are a slow and cumbersome operation we have recently work to remove in v2.4.

I'm open to re-evaluate the idea but I see a lot of problems (i.e. I don't plan to work on it but if someone want, he/she is welcome).

**Comment by melMass** [comment]
You are right I understand the extra complications it implies!
Then I think my request would me more about simplifying the way to register them, don't you think?

I've made 3 custom textures for now (CPU only) and I'm trying to wrap my head around OpenCL but to be honest my workflow is very tedious and long, do you have recommendations in that regard? (A way to quickly iterate while developing textures)

Thanks

**Comment by Dade916** [comment]
I have already developed a concept of  generic Object "Registry" and used for few objects inside the project.
For instance, a new sampler can be added by just registering with the "Sampler register" (i.e. adding a line in 2 places, declaration + code):

1) here: https://github.com/LuxCoreRender/LuxCore/blob/3614b4e61b5f25c7677a029e2dd53838abc23a3a/include/slg/samplers/samplerregistry.h#L112
2) here: https://github.com/LuxCoreRender/LuxCore/blob/3614b4e61b5f25c7677a029e2dd53838abc23a3a/src/slg/samplers/sampler.cpp#L173

However, I was never very happy of this solution, the implementation was tricky and obscure. So I have never really extended the "Registry" concept to all project objects (i.e. materials, textures, lights, etc.).
OpenCL was also left aside and still handcrafted.

It could be redone (may be, supporting dynamic registration too) and, at least, used for CPU code. 

P.S. OpenCL code for texture (and materials) is extremely hard to read because the lack of OpenCL C support for recursion force to write some very cryptic code (i.e. evaluating textures referencing other textures becomes a complex operation while it is trivial to write in C++).

**Comment by melMass** [comment]
That's exactly the concept I'm after!
I'm not sure what you find obscure in the current implementation but being able to register objects this way would be a must (to me at least :))

I'll continue my quest adding those two textures the classic way, for now, I'm actually trying to add a few more utility nodes to be able to match my Arnold material networks more easily. I'll let you know how it goes

**Comment by Dade916** [comment]
I assume we can close this one for the moment.
