### ISSUE TITLE
with 2 or more groups of lights + certain AOVs fails

### ISSUE THREAD

**Issue by Noah-ok** [LuxCoreRender/LuxCore#336]
when I try to render with a group of lights plus all the AOVs activated I get this
<a href="https://imgbb.com/"><img src="https://i.ibb.co/m6c8PJS/2020-04-13-220009.png" alt="2020-04-13-220009" border="0"></a>

deactivating these AOVs works
<a href="https://imgbb.com/"><img src="https://i.ibb.co/StDYvcX/2020-04-13-220658.png" alt="2020-04-13-220658" border="0"></a>

LuxCoreRender 2.4 Blender 2.82a

[untitled1.zip](https://github.com/LuxCoreRender/LuxCore/files/4472635/untitled1.zip)

**Comment by Dade916** [comment]
@Theverat this should be consider (somewhat) a BlendLuxCore bug: LuxCore does a lexical sort of imagepipelines names because they are not required do be numbers. So the following order of image pipelines will be defined in the attached test scene:

```
film.imagepipelines.0
film.imagepipelines.1
film.imagepipelines.10
film.imagepipelines.11
film.imagepipelines.12
film.imagepipelines.13
film.imagepipelines.2
film.imagepipelines.3
film.imagepipelines.4
film.imagepipelines.5
film.imagepipelines.6
film.imagepipelines.7
film.imagepipelines.8
film.imagepipelines.9
```
And the definition of image pipeline "10" after "1" will trigger the error (i.e. "1" name should be "01" instead).

I modified the LuxCore code so it try to sort using numerical order if the image pipeline names can be converted to a number. So it now works fine even with the above order. It should be more intuitive.

**Comment by Theverat** [comment]
Ok, I have addressed this in https://github.com/LuxCoreRender/BlendLuxCore/commit/5b3744e3259ac02a8c260bd1726488ff20c2f23b
