### ISSUE TITLE
Crash when caustic chache is enabled

### ISSUE THREAD

**Issue by zareami10** [LuxCoreRender/LuxCore#344]
It might be a bit tricky to reproduce, I have provided a blender test scene which happens to crash after just a few seconds of rendering.
Also when there is no crash, rendering is both very slow, and the render window keeps minimizing (sounds like a blender add-on issue).
Using daily builds.
[Caustic Cache Crash.zip](https://github.com/LuxCoreRender/LuxCore/files/4496598/Caustic.Cache.Crash.zip)

**Comment by Theverat** [comment]
I can not reproduce a crash on Windows 10, Nvidia GPU.
What's your OS and hardware?

**Comment by zareami10** [comment]
> I can not reproduce a crash on Windows 10, Nvidia GPU.
> What's your OS and hardware?
Currently the same, 960m 4GB (445.75) and i7-4720HQ on Windows 10 (1909).
And well the crash only happens on OpenCL, and since I just noticed that .75 isn't the latest driver version I will give the .87 a try to see if it makes any difference.

**Comment by Theverat** [comment]
I tested your file as is (it's set to OpenCL).

**Comment by zareami10** [comment]
Tested the latest driver, still crashing.
Anyways to provide debug info?

**Comment by acasta69** [comment]
It crashes also here (Windows 10 1903, GTX970 442.74, i7-4770).
This is the last part of Blender console output:
`[LuxCore][79.547] Starting 8 native render threads
Session started in 18.1 s
[LuxCore][79.968] Film hardware image pipeline
[LuxCore][79.968] Film hardware device used: GeForce GTX 970 Intersect (Type: OPENCL_GPU)
[LuxCore][79.968]   Device OpenCL version: OpenCL 1.2 CUDA
Error   : Unrecognized Exception
Address : 0x00007FF9CFC3A799
Module  : C:\WINDOWS\System32\KERNELBASE.dll`

While this is LuxcoreUI output:
`[LuxCore][40.250] Starting 8 native render threads
[LuxCore][40.422] Film hardware image pipeline
[LuxCore][40.422] Film hardware device used: GeForce GTX 970 Intersect (Type: OPENCL_GPU)
[LuxCore][40.422]   Device OpenCL version: OpenCL 1.2 CUDA
[LuxCore][44.031] [PathOCLRenderThread::0] Rendering thread ERROR: clFinish(CL_INVALID_COMMAND_QUEUE)`

**Comment by Dade916** [comment]
The problem is int he caustic cache with a combination of high photon count (1,000,000) and very large radius (7.5cm). The number of (overlapped) photons makes the look up nearly a linear process (i.e. very slow).

When using periodica cache update, you can and should use a quite small amount of photons: there are replaced at each updated so using 100,000 photons in 10 steps is like using 1,000,000 without periodic update.

I rendered the scene with 100,000 photons and a radius of 0.5cm:

path.photongi.caustic.maxsize = 100000
path.photongi.caustic.lookup.radius = 0.005

I added also a bit of clamping:

path.clamping.variance.maxvalue = 10

and the result is:

![RGB_IMAGEPIPELINE_0](https://user-images.githubusercontent.com/3247881/81166313-d3869b00-8f93-11ea-86f8-b0ae89811101.png)

If I use your settings I get a HUGE slowdown of the rendering (but no crash with latest version).

P.S. don't use Metropolis sampler on GPUs, it doesn't work well and it is worse than normal Sobol in your scene.
