### ISSUE TITLE
LuxCore fails to build with boost 1.73 due to placeholder namespace change

### ISSUE THREAD

**Issue by luyatshimbalanga** [LuxCoreRender/LuxCore#449]
Due to the [switch to c++14 inside openvdb 7.1.0](https://github.com/AcademySoftwareFoundation/openvdb/issues/795), LuxCore will no longer build. 
Unfortunately, I am unable to find a way to swich -std to c++14 so suggestion is needed.
Here is 
[build.log](https://github.com/LuxCoreRender/LuxCore/files/5250473/build.log)

**Comment by Dade916** [comment]
OpenVDB v7.0 is intentionally included inside the repository (https://github.com/LuxCoreRender/LuxCore/tree/master/deps/openvdb-7.0.0/openvdb) to avoid this kind of problems, do you have any particular reason to use OpenVDB v7.1 over v7.0 ?

**Comment by luyatshimbalanga** [comment]
The Fedora build system has openvdb-7.1.0. In default setting as seen on the attached build.log, the failure happened on dep/openvdb-7.0.0. Is there a way to adjust that? See the spec file on the cmake section : https://src.fedoraproject.org/rpms/luxcorerender/blob/master/f/luxcorerender.spec

**Comment by luyatshimbalanga** [comment]
It turned out the cause of built failure is the change done in [boost 1.73](https://www.boost.org/users/history/version_1_73_0.html) regarding the placeholder namespace. 
Additionally, LuxCore successfully built with -std=c++14. Here is the patch including the solution. I edited the title to reflect the finding from the Fedora team.
[LuxCore-use-cxx-standard-14.patch.txt](https://github.com/LuxCoreRender/LuxCore/files/5252245/LuxCore-use-cxx-standard-14.patch.txt)

**Comment by Dade916** [comment]
We have specific build Environment for Linux available here: https://github.com/LuxCoreRender/LinuxCompile

It is pretty much a static build in order to have something that will work on most Linux distributions and all the mess of different library versions available out there.
Using different versions from the one we have tested may introduced unknow bugs (and has in the past) so we can not support it.

Thanks for the patch, I guess it can stay here for future reference and anyone interested.
