### ISSUE TITLE
Red fringe when using dispersion on a sphere

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#47]
I noticed a red fringe on a sphere with dispersion enabled (cauchyc 0.05).

![red_fringe1](https://user-images.githubusercontent.com/1584761/35093163-ea391f7c-fc41-11e7-808a-cd8be82901c9.jpg)

Higher cauchy c value (0.2) makes it stronger:
![red_fringe2](https://user-images.githubusercontent.com/1584761/35093166-ece0d922-fc41-11e7-8942-bf31dee4a268.jpg)

I went back to 765fb611bef8bf3cadf037b4cf8e1daed1559c50 and it shows the same red fringe.
So I do not think it was introduced in the latest glass sampling changes.
![765fb611bef8bf3cadf037b4cf8e1daed1559c50](https://user-images.githubusercontent.com/1584761/35093189-fb3469c6-fc41-11e7-9d90-c860340c2680.jpg)

Classic API does not show this kind of fringe.
![classic](https://user-images.githubusercontent.com/1584761/35093274-397ef890-fc42-11e7-8e13-7283582ff1f4.jpg)

Testscene:
[00019.zip](https://github.com/LuxCoreRender/LuxCore/files/1642443/00019.zip)

**Comment by Dade916** [comment]
Side note: the attached test scene has ".visibility.indirect.*" set false for the sky, it can be very confusing.

They posted rendered images have a normal sky. It may be a bug in FILESAVER or BlendLuxCore.

**Comment by Theverat** [comment]
> Side note: the attached test scene has ".visibility.indirect.*" set false for the sky, it can be very confusing.

Sorry, a leftover from an old test. 
The images were rendered with BIDIR which does not use this setting as far as I know.

**Comment by Dade916** [comment]
The difference is due to a different formula used for B term of the Cauchy's equation. Our was suggested by Neo here: https://github.com/LuxCoreRender/BlendLuxCore/commit/d3fed046ab62e18226e410b42a16ca1bccefb530#commitcomment-26617643

While old LuxRender uses B=IOR.

This is the code:

```
static float WaveLength2IOR(const float waveLength, const float IOR, const float C) {
	// Cauchy's equation for relationship between the refractive index and wavelength
	// note: Cauchy's lambda is expressed in micrometers while waveLength is in nanometers

	// This is the formula suggested by Neo here:
	// https://github.com/LuxCoreRender/BlendLuxCore/commit/d3fed046ab62e18226e410b42a16ca1bccefb530#commitcomment-26617643
	// Compute IOR at 589 nm (natrium D line)
	//const float B = IOR - C / Sqr(589.f / 1000.f);

	// The B used by old LuxRender
	const float B = IOR;

	// Cauchy's equation
	const float cauchyEq = B + C / Sqr(waveLength / 1000.f);

	return cauchyEq;
}
```

I switched to the same B and I'm obtaining the same results:

![rgb_imagepipeline](https://user-images.githubusercontent.com/3247881/35123644-6a815b66-fca3-11e7-9b7c-5f4165a31908.png)

For the moment, I committed the LuxRender's formula, may be @neo2068  can further investigate/explain how B should be computed.

P.S. this stuff doesn't stop to amaze me, it is mind blowing to do in 50 in lines of code the same work LuxRender was doing with his arsenal of spectral rendering. LuxCore really render the same stuff. Someone should write a paper on this stuff.

**Comment by Dade916** [comment]
I mean the dispersion of the sun highlight on the sphere is better in LuxCore version, ahaha !

**Comment by Theverat** [comment]
![1450748043062](https://user-images.githubusercontent.com/1584761/35125877-83a3cda6-fcab-11e7-98fe-2e3cac523f5d.png)

**Comment by neo2068** [comment]
I briefly explained the formula here
https://github.com/LuxCoreRender/BlendLuxCore/commit/d3fed046ab62e18226e410b42a16ca1bccefb530#commitcomment-26617643

The IOR in the literature is measured at a fixed wavelength, i.e. 589nm (Natrium D line) @ 20°C. To model the dispersion of white light into the different colors you need the IORs for each wavelength of the visible spectrum. Therefor Cauchy proposed to fit a curve onto the measured IORs at different wavelength and describe the dispersion with the coefficients of this fitting curve. 

`IOR(lambda) = B + C/lambda^2`

If you have the IOR at 589 nm and the C coefficient (which we expose as the dispersion parameter) you could calculate the B coefficient with the above formula (the wavelength has to be in µm!)

`IOR(0.589) = B + C/0.589^2 <=> B = IOR(0.589) - C/0.589^2`

Which is the formula in the code.
For example the IOR for borosilicate crown glass BK7 is 1.5168. The cauchy coefficients are 
B = 1.5046 and C = 0.0042. With the above formula you get 

`B = IOR(0.589) - C/0.589^2 = 1.5168 - 0.0042/0.589^2 = 1.5046`

I think that the formula should be physically correct. If you use the IOR directly as the B coefficient you get a too high IOR.
![grafik](https://user-images.githubusercontent.com/17701407/35182976-6f8e5406-fdde-11e7-9b58-12ca2d5f3043.png)

**Comment by Theverat** [comment]
> I think a value of 0.05 or 0.2 for the dispersion parameter, i.e. cauchy C coefficient is way to big. A normal range should be about 0.002 - 0.015.

I'm aware, I wanted to exaggerate the effect so it is easier to see.

> I think that the formula should be physically correct. If you use the IOR directly as the B coefficient you get a too high IOR.

Does that mean that LuxRender did it wrong all these years?
And how do we remove the red fringe if we switch back to the other formula?

**Comment by neo2068** [comment]
> While old LuxRender uses B=IOR.

In the cauchytexture code of old LuxRender is a conversion formula
[https://bitbucket.org/luxrender/lux/src/f56582df55f42928ca409f5dba909b2019ca9e8e/textures/cauchytexture.cpp?at=default&fileviewer=file-view-default#cauchytexture.cpp-37](url)
which divides with `WAVELENGTH_START*WAVELENGTH_END` instead of `WAVELENGTH_D*WAVELENGTH_D`. 
When I add the cauchytexture conversion to the chart above I get the yellow line. In the fresnelcauchy code there is B=IOR which is wrong in my opinion.  We have to check which calculation is correct. 

![grafik](https://user-images.githubusercontent.com/17701407/35193596-32a4673e-fea5-11e7-8db8-de95ad372659.png)
