### ISSUE TITLE
Cannot compile OpenCL kernel for Intel UHD Graphics device in version 2.4

### ISSUE THREAD

**Issue by Looooong** [LuxCoreRender/LuxCore#512]
# Problem
When using PATHOCL render engine in LuxCore 2.4, the program hangs when compiling kernel for Intel UHD Graphics device. Even if I wait for an hour, it still hangs there and doesn't output anything in the console. The process comsumes around 8GB of RAM while compiling. In LuxCore 2.3, it only takes around a minute to compile the kernel. It compiles normally for the Intel CPU and NVidia GPU.

## Specs
+ OS: Windows 10, build 19041, 64-bit
+ Processor: Intel Core i7-10750H @ 2.60GHz (12 CPUs)
+ Memory: 16384MB
+ GPU 1: Intel UHD Graphics
  + Driver: 26.10.100.7642
  + VRAM: 128MB
  + Shared Memory: 8102MB
+ GPU 2:  NVidia GeForce RTX 2070
  + Driver: 27.21.14.6109
  + VRAM: 8031MB
  + Shared Memory: 8102MB

## clinfo
```
Platform #0: Intel(R) OpenCL
 +-- Device #0: Intel(R) UHD Graphics
 `-- Device #1: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Platform #1: NVIDIA CUDA
 `-- Device #0: GeForce RTX 2070
```

**Comment by Theverat** [comment]
In v2.4 the OpenCL code was reworked, you can read more about it here: https://wiki.luxcorerender.org/LuxCoreRender_Release_Notes_v2.4#About_Performance_on_GPUs
As a result, it is now much more complex (with the benefit of only needing to be compiled once). You should report this issue to the graphics card vendor, as it is a problem of their OpenCL compiler.

**Comment by Looooong** [comment]
Thanks for the info. Is there anyway I can do to debug the compiler to see what's going on with it?

**Comment by JundaFeng** [comment]
Hi, I was running into the same issue. It turns out that the Intel HD Graphics may have some issue with double precision FLOPs.
Thus, my naive vector addition kernel will compile after I removed the "#pragma OPENCL EXTENSION cl_khr_fp64 : enable" and changed the data type from double to float.

**Comment by u3dreal** [comment]
Wow nice can you be a bit more specific where you removed it ?? 
On Mac this does not work .. for at least a year  -.. maybe it help wanna try ..

**Comment by JundaFeng** [comment]
> Wow nice can you be a bit more specific where you removed it ?? On Mac this does not work .. for at least a year -.. maybe it help wanna try ..

Hi, my issue is simply related to the OpenCL kernel and I have to say I have no further knowledge about LuxCoreRender. But as you have the same issue related to Intel UHD Graphic, I guess it may be due to the limitation of the Intel GPU (some operations may be supported by CPU/NV GPU but not okay on Intel GPU). 

For example, in my simple vector add kernel (https://github.com/JundaFeng/test_opencl_dev_query_vector_addtion_intel_nvidia_cpu-x-1_gpu-x-2/blob/main/vec_add.cpp), the kernel will not compile at runtime if you do not comment the pragma (line 98) and let the floating-point datatype be double-precision. 

Sorry for not mentioning the exactly same issue and letting you down.

**Comment by u3dreal** [comment]
OK thanks for ckearing it up
