### ISSUE TITLE
Example `luxcorescenedemo` doesn't start / produces weird output except for the first frame

### ISSUE THREAD

**Issue by tschw** [LuxCoreRender/LuxCore#76]
The `sky` light source seems to have been removed or renamed. Removing its instantiation, I see a first frame that basically looks OK:

![image0](https://user-images.githubusercontent.com/3916357/37840418-46ae87da-2ebd-11e8-9cbf-fda459d86533.png)

But further frames not so much:

![image1](https://user-images.githubusercontent.com/3916357/37840472-77064580-2ebd-11e8-927f-dbc5fa9764b6.png)

![image2](https://user-images.githubusercontent.com/3916357/37840497-8a6cd2ba-2ebd-11e8-9dfc-dc524bba4f74.png)

![image3](https://user-images.githubusercontent.com/3916357/37840514-91cfe790-2ebd-11e8-991a-5400f070cd4c.png)

![image4](https://user-images.githubusercontent.com/3916357/37840532-a352c4e2-2ebd-11e8-842a-4ec7e9d67e8f.png)

**Comment by Theverat** [comment]
> The sky light source seems to have been removed or renamed.

Yes, it is deprecated, there's only `sky2` now.

**Comment by tschw** [comment]
> Yes, it is deprecated, there's only `sky2` now.

I figured that it wouldn't be gone gone (so no commits for removal).

> We should update the test scenes and wiki.

Yes. There's no obvious reason for that output in the example, however. That might be a more serious bug.

**Comment by Dade916** [comment]
> Yes. There's no obvious reason for that output in the example, however. That might be a more serious bug.

It is an error in luxcorescendemo introduced in this commit: https://github.com/LuxCoreRender/LuxCore/commit/d065c44bf2646314e2b986f8e1ccd852a3aecb4c#diff-64ba1cb43ee5e03a96216061512800c1

I was assuming the demo was doing just a single rendering and I was waiting for the end of the rendering session with "HasDone()". 
However it does 5 renderings and the last 4 run just for few ms because I'm already after the 10secs halt condition after the first one (the rendering was also written over the previous one).

I should have fixed the problem.
