### ISSUE TITLE
Artefacts in render of simple object

### ISSUE THREAD

**Issue by ajmurrell** [LuxCoreRender/LuxCore#79]
The render shows artefacts of simple triangulated surface
![lux_hddmarkup](https://user-images.githubusercontent.com/37913804/38110907-c26ec11a-3362-11e8-8e3f-daada1f8df7b.png)
Tested with Cycles and RenderMan, neither show this problem. File was converted from CAD to stl.  Running Alpha 7 of LuxCore on Linux Mint 18.3, GTX 970 and AMD Ryzen 1700.

**Comment by ajmurrell** [comment]
Forgot to apply the scale on the file I provided in the zip, but I did apply it on the test scene I used to produce the image in the initial post. Sorry, tired.

**Comment by Theverat** [comment]
Min and max epsilon are currently not exposed in BlendLuxCore.
I have this issue about it: https://github.com/LuxCoreRender/BlendLuxCore/issues/24
Is there some algorithm we can use to automatically find good values for min/max epsilon?

**Comment by Dade916** [comment]
I can confirm that the source of the problem is the object scale:

```
Object name: Mesh_HDDrack_140595502187016000
BBox[Point[-0.00199997, -0.119998, 0.00154629], Point[0.121998, 0, 0.150544]]
```

The object is very small for LuxCore, it has a width of about 10cm. If I set the epsilon value to:

```
scene.epsilon.min = 0.001
scene.epsilon.max = 0.001
```

I get this error free rendering:

![eps](https://user-images.githubusercontent.com/3247881/38140239-2dc2f1e0-3433-11e8-870d-ef95ad8ec713.jpg)

I don't know how Blender unit management works but, looking at the Blender file, the object seems to be scaled down by "0.001" and so it is very small (1000 times smaller than usual) for LuxCore. @ajmurrell, you  can fix the problem by changing the object scale or by adapting the epsilon value used as listed above (after the support has been added to LuxCore Blender plugin).

P.S. Simon, there isn't a way to adapt epsilon min/max values. The problem is intrinsic in the nature of the vary low precision (and variable resolution) of 32bit floating point numbers.

**Comment by ajmurrell** [comment]
Yes the scale is screwed up on the blend file I provided, but the original render was scaled down and the scale applied.  There is an issue with scale coming from the CAD package I used to blender's units, though they are both metric, blender adds a few digits (3) to the actual measurements. But from what I am gathering, there is a minimum object size for a clean render? Are we talking that we need object sizes in the meter range?

**Comment by Theverat** [comment]
> But from what I am gathering, there is a minimum object size for a clean render? Are we talking that we need object sizes in the meter range?

Yes and no.
If we say that the floating point number 1.0 always equals 1 meter, then yes.
But floating point numbers do not have inherent units, so depending on the scene you can redefine them and say that 1.0 equals 1mm or 1km.

Related: 
* https://github.com/LuxCoreRender/BlendLuxCore/issues/97
* https://forums.luxcorerender.org/viewtopic.php?f=4&p=1733#p2064

It is something I have to fix in the addon, but it is a larger refactor.

**Comment by Dade916** [comment]
There is a covenant in Lux, it assumes 1 is 1 meter and the default values of some parameter is picked according this convention.
If you use a scale significantly far from covenant (like 1000 times), you have to set the other parameters according the new scale (like what is considered an "epsilon" or bump mapping scale, etc.).

This is true for any computer application approximating real numbers with (very) finite precision of 32 bit floating numbers. It is true for all rendering programs, CAD, etc. It may be different where the problem starts to be noticeable (10, 100, 1000, 10.000 scale) but you are always going to hit a wall.

As you have noticed GPUs has often a lower than CPUs precision. This is not due to some intrinsic limit but more likely to some short cut taken by vendors in the implementation of OpenCL standard (it shouldn't happen but it does and quite often).

**Comment by Theverat** [comment]
Ok, what should I put as sensible min, max and description?

**Comment by Theverat** [comment]
With min/max I meant the minimum and maximum values the user is allowed to set for the max. epsilon.
For the min. epsilon I chose `min=1e-6, max=0.1`.

**Comment by Dade916** [comment]
The only rule is "max. epsilon >= min epsilon", after that there are just too many factors to have a fixed rule.

P.S. it may be better to use min=1e-5 as default value, it is a bit more GPU friendly.

**Comment by Theverat** [comment]
> P.S. it may be better to use min=1e-5 as default value, it is a bit more GPU friendly.

It is the default.
Ok it's in: https://github.com/LuxCoreRender/BlendLuxCore/commit/3a871345b34d6d7db638873c07d1f8a6a0fbcbf0
