### ISSUE TITLE
LuxCore crashes when using more motion steps than Embree allows

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#84]
From the [embree API page](https://embree.github.io/api.html):
> All geometry types support multi-segment motion blur with an arbitrary number of equidistant time steps (in the range of 2 to 129).

When the user tries to set >= 130 time steps in LuxCore, it crashes without error message.
I think it would be nice if a runtime error would be thrown in this case.

I edited the wiki page to include a note about this: https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.0#Object_Motion_Blur

**Comment by Dade916** [comment]
I have added safety check when using more than 129 motions steps with Embree.

Interesting side node: MBVH (i.e. the OpenCL default and potentially usable on the CPU too) works with more than 129 steps even if using Embree to build the accelerator structure (because a bounding box of all steps is passed to Embree, no matter of the number of steps).
