### ISSUE TITLE
No caustics in Unidirectional Path tracer

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/LuxCore#86]
version: 2.0 beta1
blender : 2.79b
Issue:
I suppose caustics effect can be achieved by long time rendering using PathCPU or PathOCL and get same result  with Bidi engine. So I did a test but after 50000 samples, there was still no caustics effect. Is there anything I can set to enable caustics in Path engine? 
And the difference of color in these render results (including cycles) confuse me. they are just so different. 

[glass.zip](https://github.com/LuxCoreRender/LuxCore/files/1871125/glass.zip)
PATH:
![path](https://user-images.githubusercontent.com/8104251/38244647-84546f76-377a-11e8-9ca7-c3820067cba0.jpg)
BIDI: 500 samples
![bidi](https://user-images.githubusercontent.com/8104251/38244885-3a76b2c8-377b-11e8-8651-caf94f7023b3.jpg)
Cycles: 5000 samples
![cycles](https://user-images.githubusercontent.com/8104251/38245270-96789f40-377c-11e8-8aa9-e8232eecb88e.jpg)

**Comment by Dade916** [comment]
`I suppose caustics effect can be achieved by long time rendering using PathCPU or PathOCL and get same result with Bidi engine.`

Nope, it depends on what type of light source you are using. You need an "intersectable" light source to be able to get caustics out of a path tracer.  A point light sources, in LuxCore, are not directly intersectable (no matter of the radius) and can not generate any caustics. This happen because a path tracer can render a caustic only if it a path starting from the camera can hit the light sources.

I assume Cycles point lights are intersectable and directly visible by the camera (they are not in LuxCore) and this explain the different behavior of the path tracers.

Just replace the point light with a small triangle/quad light source. It can be intersected, and so the LuxCore path tracer will be able to render caustics. Even if, smaller is the light source, smaller is the probability of an hit and more the caustics will look like a confused group of fireflies (like in Cycles) instead of a sharp caustic.

**Comment by frankyifei** [comment]
Thanks a lot. I figure better using Bidi engine for this.  But there are some differences compared to Path Engine's result, like the small triangle in the water.

**Comment by Dade916** [comment]
The small triangle is likely to depends on how the water has been modeled. It is tricky (more than one could tough). It is important how the geometry is made or you may end with some "air" between the water and glass. This very old video https://vimeo.com/groups/27884/videos/21139061 may contain some hint (it is about the old Lux but the concepts are still the same).

LuxCore also supports volume priorities in order to make this task easier. I'm not a Blender expert so I can not help you very much but if you open a topic on our forum, you should receive the help of people with Blender experience that can tell you exactly how to build the geometry.

**Comment by frankyifei** [comment]
Thanks. I'll close this issue.

**Comment by Theverat** [comment]
> LuxCore also supports volume priorities in order to make this task easier. I'm not a Blender expert so I can not help you very much but if you open a topic on our forum, you should receive the help of people with Blender experience that can tell you exactly how to build the geometry.

You should build your geometry this way:

![unbenannt](https://user-images.githubusercontent.com/1584761/38259653-da27e67c-3765-11e8-8ee0-9b1c907b6ffb.png)
* Turquoise outline: glass mesh boundary
* Dark blue outline: fluid mesh

Volumes:
* fluid volume: priority 0
* glass volume: priority 1 (so it overrides the fluid volume where the two overlap, this happens in the green area in the image)
You can also use different numbers. Higher priority overrides lower priority.
